DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS lanes;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS page_contents;
DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "pgcrypto";
