apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glyph.fullname" . }}-migrations
  labels:
    {{- include "glyph.labels" . | nindent 4 }}

data:
  {{- range $path, $bytes := .Files.Glob "migrations/*.sql" }}
  {{ base $path }}: |
    {{- toString $bytes | nindent 4 }}
  {{- end }}
