{{- if not .Values.api.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glyph.fullname" . }}-session
  labels:
    {{- include "glyph.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.api.sessionSecret }}
data:
  secret: {{ .Values.api.sessionSecret | b64enc | quote }}
{{- else }}
stringData:
  secret: ""
{{- end }}
{{- end }}
---
{{- if and .Values.api.oidc.enabled (not .Values.api.oidc.existingSecret) (not .Values.api.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glyph.fullname" . }}-oidc
  labels:
    {{- include "glyph.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.api.oidc.clientSecret | b64enc | quote }}
{{- end }}
